### ISSUE TITLE
Exception encountered, of type "RuntimeException" when using #ask

### ISSUE THREAD

**Issue by Lamenax** [SemanticMediaWiki/SemanticMediaWiki#1471]
Hello everyone,

Since I installed Mediawiki, I face a disturbing an error when using `#ask`.
Not everytime, but only when the category I am looking for contains sub-categories.

For instance if CatA has got a sub category CatB, and if CatB doesn't have any subcategory, then :
   -`{{ #ask: [[Category:CatB]] | ?Property }}` will work just fine
   -`{{ #ask: [[Category:CatA]] | ?Property }}` won't work, and will generate the following error as soon as I click on "save my modifications": 

> Exception encountered, of type "RuntimeException"

I can not reproduce that mistake here on SMW sandbox.
I already tried to make a new mediawiki install but did not solve the issue.
Could that be related to an extension I do not have?

Thank you for your help.

**Comment by mwjames** [comment]
> I can not reproduce that mistake here on SMW sandbox.

Chances are that it has already been fixed (the sandbox is running the latest master) or an extension is meddling with a result but to be sure and since "Exception encountered, of type "RuntimeException"" doesn't contain enough information please enable the stack trace [0, 1] and post the results here.

[0] https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs
[1] https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs/stack_trace

**Comment by Lamenax** [comment]
Ok, so I did what was on your links, I am not sure where I should read the log (on the bottom of my window I just clicked on "Console"), this is what I got:
```
Use of Parser::uniqPrefix was deprecated in MediaWiki 1.26.
Use of wfMsg was deprecated in MediaWiki 1.21.
Use of wfMsgReal was deprecated in MediaWiki 1.21.
Use of wfMsgGetKey was deprecated in MediaWiki 1.21.
```

I do have 421 lines of "Debug log", but before posting anything I'd like to be sure that's what you are looking for.

One curious thing: by doing so, my `#ask` request succeeded in returning one of the three results it was supposed to return! For your information, it was a request with Timeline output format, and only one date came in. But the issue happens for any kind of output format, I already checked that.

**Comment by mwjames** [comment]
> Ok, so I did what was on your links, I am not sure where I should read the log (on the bottom of my window I just clicked on "Console"), this is what I got:

This is the wrong place (`RuntimeException` is not about the browser). If you encounter some thing like "Exception encountered, of type "RuntimeException"" you should find an output as in [0].

[0] https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs/stack_trace

**Comment by mwjames** [comment]
> I'd like to be sure that's what you are looking for.

To find an actual stack trace (not related to your reported issue; #1473) example, see:

http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AAsk&q=[[Has+coordinates%3A%3A%2B]]&po=Has+coordinates&eq=yes&p[format]=openlayers&sort_num=&order_num=ASC&p[source]=&p[limit]=&p[offset]=&p[link]=all&p[sort]=&p[headers]=show&p[mainlabel]=&p[intro]=&p[outro]=&p[searchlabel]=%26hellip%3B+autres+r%C3%A9sultats&p[default]=&p[class]=sortable+wikitable+smwtable&p[sep]=&eq=yes

**Comment by Lamenax** [comment]
Well, I did what was on [0], but I do not get such an output! You can see what I get in [1].
If I understand well, I should have, after actualising the page I am interested in, the same kind of log you showed me as an exemple?

[0] https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs
[1] http://sandbox.semantic-mediawiki.org/wiki/Fichier:1471_-_1.png

**Comment by mwjames** [comment]
> http://sandbox.semantic-mediawiki.org/wiki/Fichier:1471_-_1.png

I can see from the picture you have uploaded that message emitted is by `Lingo:parse` which is from Lingo extension [0] not SMW and extension `PdfBooksHooks` is showing some messages.

[0] https://www.mediawiki.org/wiki/Extension:Lingo

**Comment by mwjames** [comment]
> ... the same kind of log you showed me as an exemple?

You only get those stack traces when it is an actual Exception.

**Comment by mwjames** [comment]
> {{ #ask: [[Category:CatA]] | ?Property }} won't work, and will generate the following error as soon as I click on "save my modifications":

If you have #ask query that encounters an Exception then it will show (given that the stack trace is enabled) as seen in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1471#issuecomment-201270959.

**Comment by Lamenax** [comment]
Ok, I still don't have something like what you showed me, but I got this on the webpage;
Warning: preg_match_all(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 954

```
Warning: preg_replace(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 960

Warning: preg_match_all(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 954

Warning: preg_replace(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 960

Warning: preg_match_all(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 954

Warning: preg_replace(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 960

Deprecated: Use of wfMsg was deprecated in MediaWiki 1.21. [Called from PdfBookHooks::onSkinTemplateNavigation in /var/www/mediawiki/extensions/PdfBook/PdfBook.hooks.php at line 167] in /var/www/mediawiki/includes/debug/MWDebug.php on line 300

Deprecated: Use of wfMsgReal was deprecated in MediaWiki 1.21. [Called from wfMsg in /var/www/mediawiki/includes/GlobalFunctions.php at line 1489] in /var/www/mediawiki/includes/debug/MWDebug.php on line 300

Deprecated: Use of wfMsgGetKey was deprecated in MediaWiki 1.21. [Called from wfMsgReal in /var/www/mediawiki/includes/GlobalFunctions.php at line 1586] in /var/www/mediawiki/includes/debug/MWDebug.php on line 300
```

What I observe is that each time I go to another page of my wiki, there are twice as much as those warnings! And it keeps increasing at each refreshing.
I think there must be some recursive call somewhere, don't you think?

**Comment by Lamenax** [comment]
FYI, there was lingo installed with an old version (1.2) because it seemed like semantic-glossary would not work with lingo 2.0 or newer.
I installed lingo 2.0, updated the whole thing with Semantic-Glossary in my composer.json file, but now Semantic-Glossary is not working anymore. I am not sure I have a clue of what is going on.

**Comment by mwjames** [comment]
> Warning: preg_replace(): Compilation failed: two named subpatterns have the same name at offset 785 in /var/www/mediawiki/includes/MagicWord.php on line 960

> Deprecated: Use of wfMsg was deprecated in MediaWiki 1.21. [Called from PdfBookHooks::onSkinTemplateNavigation in 

Errors metioned in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1471#issuecomment-201321303 are not emitted by SMW therefore are not relevant for the original issue.

> I installed lingo 2.0, updated the whole thing with Semantic-Glossary in my composer.json file, but now Semantic-Glossary is not working anymore. I am not sure I have a clue of what is going on.

Should be posted on https://github.com/SemanticMediaWiki/SemanticGlossary.

**Comment by mwjames** [comment]
Unless I see a ""RuntimeException" when using #ask" to the original `{ #ask: [[Category:CatA]] | ?Property }}` inquiry, I cannot help.

**Comment by Lamenax** [comment]
Ok I get it, actually with the debug feature I found a lot of things which were not supposed to work properly!

I updated a lot of things too, at the end I succeedeed in doing my `#ask` requests as I wanted to (no more runtime exception), but it seems that I can not have the latest Semantic glossary version and everything else working fine at the same time... But that is another issue.

Thank you for the debugging tools, I will investigate further on my own next time!
Have a great week-end.

**Comment by s7eph4n** [comment]
Make sure you correctly (according to instructions) install the latest version of SemanticGlossary. If you them still have problems raise a problem on SemanticGlossary (see @myjames link).

**Comment by Lamenax** [comment]
I did install the latest version of semantic glossary, but I was experiencing several issues: the glossary page was blank, or the popup when you fly over a glossary term would not show... 

Updating everything, running rebuildGlossaryCache.php and rebuilData.php in SemanticMediaWiki, and writing `$wgIncludejQueryMigrate = true;` in my LocalSettings.php file seemed to answer those troubles (it is not written in the standard procedure). I was then (at least!) able to see what stack traces looked like!

Something else, but to understand more I will have to read more I guess: to me, when using the composer, I did not have to add any `wfLoadExtension` in my LocalSettings.php. But apparently, adding `wfLoadExtension('SemanticGlossary');` is mandatory in order to make everything work (but only mandatory for that extension).

Thus being said, I won't add more on this thread, as I understood this is not the right place to talk about SemanticGlossary! Just wanted to answer you and thank you.
